hardware_control_loop:
  loop_hz: 1000
rokae_hardware_interface:
  joints: &id001
  - joint1
  - joint2
  - joint3
  - joint4
  - joint5
  - joint6
  - joint7
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 1000
position_joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints: *id001
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.05
    joint1:
      goal: 0.05
    joint2:
      goal: 0.05
    joint3:
      goal: 0.05
    joint4:
      goal: 0.05
    joint5:
      goal: 0.05
    joint6:
      goal: 0.05
    joint7:
      goal: 0.05
  stop_trajectory_duration: 0.5
  state_publish_rate: 100.0
  action_monitor_rate: 20.0
velocity_joint_trajectory_controller:
  type: velocity_controllers/JointTrajectoryController
  joints: *id001
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.05
    joint1:
      goal: 0.05
    joint2:
      goal: 0.05
    joint3:
      goal: 0.05
    joint4:
      goal: 0.05
    joint5:
      goal: 0.05
    joint6:
      goal: 0.05
    joint7:
      goal: 0.05
  gains:
    joint1:
      p: 500
      i: 0.05
      d: 0.1
      i_clamp: 1
    joint2:
      p: 500
      i: 0.05
      d: 0.1
      i_clamp: 1
    joint3:
      p: 500
      i: 0.05
      d: 0.1
      i_clamp: 1
    joint4:
      p: 500
      i: 0.05
      d: 0.1
      i_clamp: 1
    joint5:
      p: 500
      i: 0.05
      d: 0.1
      i_clamp: 1
    joint6:
      p: 500
      i: 0.05
      d: 0.1
      i_clamp: 1
    joint7:
      p: 500
      i: 0.05
      d: 0.1
      i_clamp: 1
  stop_trajectory_duration: 0.5
  state_publish_rate: 100.0
  action_monitor_rate: 20.0
torque_joint_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints: *id001
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.05
    joint1:
      goal: 0.05
    joint2:
      goal: 0.05
    joint3:
      goal: 0.05
    joint4:
      goal: 0.05
    joint5:
      goal: 0.05
    joint6:
      goal: 0.05
    joint7:
      goal: 0.05
  gains:
    joint1:
      p: 9
      i: 0.1
      d: 0.2
      i_clamp: 1
    joint2:
      p: 9
      i: 0.1
      d: 0.2
      i_clamp: 1
    joint3:
      p: 9
      i: 0.1
      d: 0.2
      i_clamp: 1
    joint4:
      p: 9
      i: 0.1
      d: 0.2
      i_clamp: 1
    joint5:
      p: 9
      i: 0.1
      d: 0.2
      i_clamp: 1
    joint6:
      p: 9
      i: 0.1
      d: 0.2
      i_clamp: 1
    joint7:
      p: 9
      i: 0.1
      d: 0.2
      i_clamp: 1
  stop_trajectory_duration: 0.5
  state_publish_rate: 100.0
  action_monitor_rate: 20.0
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints: *id001
controller_manager:
  ros__parameters:
    use_sim_time: true
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
gazebo_ros2_control:
  ros__parameters:
    use_sim_time: true
    controller_manager:
      update_rate: 1000
arm_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
